### ISSUE TITLE
Issue on page /k-python/pip.html

### ISSUE THREAD

**Issue by HappySimple** [Eugene-Forest/NoteBook#1]
sphinx能加密文档吗

**Comment by Eugene-Forest** [comment]
目前就我所知，Sphinx编写的文档的源文件似乎无法加密，如果你有这方面的需求或疑惑，可以去[Sphinx官网](https://www.sphinx-doc.org/en/master/)看看他最新版本是否有相关功能的支持。

如果是需要对Sphinx文档项目源文件进行保密的话，目前比较简单的方法是把项目挂载在到自己的服务器上。
